[package]
name = "f3_gfx"
version = "0.1.0"
authors = ["f3kilo <f3kilo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.41"
log = "0.4.11"
ktx2-reader = "0.1.2"

[dependencies.tokio]
version = "0.2.22"
features = ["rt-core", "time"]