[package]
name = "f3_gfx"
version = "0.1.0"
authors = ["f3kilo <f3kilo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
thiserror = "1.0.24"
async-trait = "0.1.48"

[dev-dependencies]
env_logger = "0.8.3"